# Homework 03

## Due Thursday, February 18th

In [2]:
import numpy as np

### 1. Vector manipulation

Create a vector of zeros of size 10 but have the fifth value be 1.

In [3]:
np.array([0,0,0,0,1,0,0,0,0,0])

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

### 2. Vector range

Create a vector with values ranging from 10 to 49, inclusive.

In [5]:
thelist = []
for i in range(10,50):
    thelist.append(i)
np.array(thelist)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3. Reverse a vector

Write a function, `reverse(x)` which reverses a vector, so that the first element becomes the last element. The API should be

    return a 1D vector with the elements reversed
    
    Input
    -----
        x: 1D array
    
    Output
    ------
        res: 1D array, with the elements of `x` reversed

Include this (or an equivalent description) in the function's docstring.

In [9]:
inlist=np.array([1, 2, 5, 9, 11, 7])
def reverse (x):
    newlist=[]
    a=0
    for i in range(len(x)):
        a = x[-1]
        x = x[:-1]
        newlist.append(a)
    return np.array(newlist)
reverse(inlist)    

array([ 7, 11,  9,  5,  2,  1])

### 4. Find indices of non-zero elements

Write a function `find_nonzero(x)` that finds the indices of non-zero elements, with an API like

    return the indices of non-zero elements of an array.

    Input:      x:  array
    Output:     indices: array of integer indices

Use the function to get out the non-zero elements from an array containing the elements [1,2,0,0,4,0].

In [13]:
test4=[1,2,0,0,4,0]
def find_nonzero(x):
    list1=[]
    for i in range(len(x)):
        if (x[i] != 0):
            list1.append(i)
    return np.array(list1)
find_nonzero(test4)

array([0, 1, 4])

### 5. Array with random values

Create a 3x3x3 array with normally distributed ($\mu =0, \sigma=1)$ random values.

In [19]:
awesome=np.random.rand(3,3,3)

for i in awesome:
    for j in i:
        for k in range(len(j)):
            j[k] = round(j[k])
print(awesome)

[[[ 0.  1.  1.]
  [ 1.  0.  1.]
  [ 1.  0.  1.]]

 [[ 1.  0.  0.]
  [ 1.  0.  0.]
  [ 0.  1.  1.]]

 [[ 0.  1.  1.]
  [ 0.  1.  1.]
  [ 0.  0.  1.]]]


### 6. Operations on an array with random values

Create a 10x10 array with random values. Find 
- the minimum value of the 2nd row
- the maximum value of the 4th column

In [27]:
xx = np.random.rand(10,10)
min(xx[1,:])
max(xx[:,3])
print (min(xx[1,:]),max(xx[:,3]))

0.0211744310833 0.91882280453


### 7. Vector without end points

Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [30]:
kk=np.array([0,.1,.2,.3,.4,.5,.6,.7,.8,.9])
kk[1:-1]

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8])

### 8. Sorted random vector

Create a random vector of size 10, then sort it.

In [37]:
dd = np.random.rand(10)

#bubble sort
a,b = 0,0
for i in range(len(dd)):
    for j in range(len(dd)-1):
        if (dd[j] > dd[j+1]):
            a = dd[j]
            b = dd[j+1]
            dd[j] = b
            dd[j+1] = a
dd

array([ 0.04633638,  0.0529527 ,  0.23235513,  0.48582956,  0.59799677,
        0.60697807,  0.76469785,  0.8305283 ,  0.86596993,  0.91695414])

### 9. Test for array equality

Write a function `is_equal(A, B)` that compare two arrays `A` and `B` and checks to see if they are equal. 

    return True if two arrays are the same shape and all the elements are equal.
    
    Inputs:
        A, B:  array
    Output:
        Bool:  True if A and B have the same shape and identical elements.

The arrays count as equal if they are the same shape and all elements in the array are equal.

In [42]:
tt=np.array([1,2,5,8,7,9,6,3,1,4,6])
yy=np.array([1,2,5,8,7,9,6,3,1,4,6])
uu=np.array([1,2,5,8,7,9,7,3,1,4,6])
oo=np.array([1,2,5,8,7,9,7,3,1,4,6])
def is_equal(A,B):
    for i in (A==B):
        if (i == False):
            return False
    return True
is_equal(oo,uu)

True

### 10. Subtract the row mean from rows of a matrix

Create a matrix. Then subtract the mean of each row of the matrix from the respective row. Do this without using a loop (that is, using array operations).

In [53]:
rr=np.random.rand(3,3)
rr[0]=rr[0]-np.mean(rr[0])
rr[1]=rr[1]-np.mean(rr[1])
rr[2]=rr[2]-np.mean(rr[2])
rr

array([[ 0.14194501, -0.37752481,  0.2355798 ],
       [ 0.10589153, -0.01387264, -0.09201888],
       [-0.09829342, -0.20280343,  0.30109685]])

### 11. Multiply arrays

Multiply an array of dimension (5,5,3) with an array with dimensions (5,5). Then multiply an array of dimension (3,5,5) with an array of dimension (5,5).

In [61]:
aa=np.random.rand(5,5,3)
bb=np.random.rand(5,5)
cc=np.random.rand(3,5,5)
dd=np.random.rand(5,5)
sol2=cc*dd
sol1=aa*bb.reshape(5,5,1)
print(sol1.shape)
print(sol2.shape)

(5, 5, 3)
(3, 5, 5)


### 12. Creating a new array

Starting with an array

    Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14].
    
Generate an array 

    R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]. 

In [64]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R = []
for i in range(len(Z)-3):
    R.append([i+1,i+2,i+3,i+4])
print(R)

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13], [11, 12, 13, 14]]


### 13. Convert from Cartesian to polar coordinates

Write a function `cart2polar(xy)` which takes in an Nx2 matrix of `x, y` pairs representing Cartesian coordinates and return the locations represented in polar coordinates in the same shape matrix. The API is

    Return equivalent polar coordinates of specified cartesian points.
    
    Inputs:
        xy: array
             Nx2 array of Cartesian coordinates, with columns x and y respectively.

    Returns:
        rp: array
            Nx2 array of polar coordinates, with columns radius and angle respectively


In [66]:
from math import *

test13 =[[1,2],[7,11],[3,17]]

def cart2polar(xy):
    thelist = []
    mag,ang = 0,0
    for i in xy:
        mag = np.sqrt(i[0]*i[0]+i[1]*i[1])
        ang = atan(i[1]/i[0])
        thelist.append([mag,ang])
    return thelist
cart2polar(test13)

[[2.2360679774997898, 1.1071487177940904],
 [13.038404810405298, 1.0040671092713902],
 [17.262676501632068, 1.396124127786657]]

### 14. Compute and time for loops and array operations.

Calculate the time it takes to do what we did in class

    a = np.arange(1024.0).reshape(4, 8, 16, 2)   # a 4D array using sequential numbers
    b = np.random.rand(4, 8, 16, 2)              # a 4D array using random numbers
    sol = a * b  # element-by-element multiplication. This operation is about as fast as it can be on your computer.

and the time required for doing the same operation with a series of 4 `for` loops, one for each dimension of the arrays. Compare the times by calculating a ratio.

In [ ]:
'Will come seek help on how to create this loop.'

### 15. Fix the code

This code needs to be fixed so that it can run properly and pass the assertion test at the bottom. Write out what you changed to make it work and why it needed to be changed.

In [76]:
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """

    aa = a[:2, :]
    aa /= 4.
    a[:2, :] -= aa
    return a*(b.reshape(2,3))
    

a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

ValueError: total size of new array must be unchanged

### 16. Calculate components of a vector

Read in file `data/burl1h2010.txt`. This file gives a bunch of data from a wind station. In particular, read in the wind direction, `WDIR`, and wind speed, `WSPD`. Then, write a function that calculates and returns the `u` and `v` components of this wind vector, which point along the x- and y-axes.

The function should have the following basic functionality:

    Take in vector and return components.
    
    Inputs:
        vdir: vector direction in degrees
        vspd: vector magnitude
        
    Returns:
        u: x component of vector
        v: y component of vector


In [124]:
from math import *
stuff = []

def remove_whitespace(s):
    out = ""
    for i in s:
        if (i!=' '):
            out += i
    return out

lines = open("burl1h2010.txt")
lines = lines.readlines()
lines = lines[2:]
for l in lines:
    spd = (int(remove_whitespace(l[17:20])))
    drn = (float(remove_whitespace(l[22:25])))
    stuff.append([spd,drn])
    
output = []
for i in stuff:
    x = cos(i[1])*i[0]
    y = sin(i[1])*i[0]
    output.append([x,y])

output

[[-132.6589945444597, 18.910081080022206],
 [-110.30128520910009, -54.430014525266856],
 [-128.37237008815242, -20.506940238622267],
 [-61.94637931694333, 2.5780010708640106],
 [-13.522646279050452, -41.87049125113871],
 [70.09243092547672, -20.397331368521588],
 [35.39766378393304, -6.557850153795451],
 [-13.666953928270154, 6.181777278626349],
 [-10.8595207571202, 11.750353565985813],
 [-280.00257001770353, -216.5976933937225],
 [-15.817246625780806, -6.230145197282782],
 [-15.410767267171464, 11.113426664943471],
 [356.0, 0.0],
 [-0.0, -0.0],
 [-0.0, -0.0],
 [-8.81257977101627, 6.583193585143522],
 [10.780732356253658, 2.1853626387456733],
 [-3.686968577706227, 3.377315902755755],
 [-16.86783053269426, 2.115725199620049],
 [-0.11679808920515526, 3.9982944121660204],
 [1.910672978251212, 0.5910404133226791],
 [0.2122116050031087, 2.9924849598121632],
 [-2.71488018928005, 2.9375883914964533],
 [349.88376828932326, 70.92495109383685],
 [-0.0, 0.0],
 [-1.356619443935338, 3.7629222267190

### 17. (Grad) Write and use a class

Consider one of the data files located in `python4geosciences/data/MCH/`. Write a class, `dataclass`, to store some of the information in the file. The class should:

* be initialized with the name of the file (without file type suffix of .cnv2), and the temperature and salinity values found in the file;
* contain a method, `salt_mean`, which returns the mean of the salinity;
* contain a method, `temp_max`, which returns the maximum value of the temperature values.

Notice that there are many data files in this directory. It would be a lot of work to read them all in by hand. Instead, write a loop which loops through the file names, reads in the necessary data, calls `dataclass` to store the data in a class instance, and adds it to a list of all of the class instances. At the end of your solution, you should have a list of all of the class instances, one for each data file. As usage examples, if your list of data objects is called `wind`, you should be able to access the temperatures from the 3rd file that is read in with

    wind[2].temp

and you should be able to calculate the mean salinity of the final file with 

    wind[-1].salt_mean()

Hint: Check out the package `glob` for reading in file names with a wild card. 

### 18. (Grad) Running mean

Write a function that computes averages using a sliding window over a vector; that is, it should take in a vector and for every element in the vector, compute the average of that point with the N points on either side of the element. N should also be an input parameter, and the function should return the original vector if N=0. The returned vector should be the same size as the input vector.

Do not use the `pandas` package or the function `convolve`; instead, use a loop. Use the following API for your function:

    Return the running average of a vector, with averaging window of size N.
    
    Inputs:
        vec: Input vector
        N (int): Averaging window size, or number of elements to include in mean on either side of each element.
    
    Outputs:
        out: Vector of running-averaged values; same size as vec
